//File contains all the data used for the front end. Any new maps or heroes added here will automatically be added to the page
//File also contains all functions used to retrieve and manipulate the data data.
var mapWeight = 1;
var counterWeight = 1;
var synergiesWeight = 1;
var tournamentWeight = 1;

var lastUpdateDate = "January 14th, 2017";

//counterScores are how well each hero counters the hero
var heroData = [
    {
        name: "Ana",
        actualName: "Ana",
        role: "Support",
        healer: true,
        sniper: true,
        builder: false,
        counterScores: {
            Ana: 0,
            Bastion: -1,
            Dva: 1,
            Genji: 2,
            Hanzo: 1,
            Junkrat: 0,
            Lucio: 1,
            McCree: 1,
            Mei: 1,
            Mercy: -2,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: 1,
            Reinhardt: 0,
            Roadhog: 1,
            Soldier76: 0,
            Sombra: 0,
            Symmetra: -1,
            Torbjorn: 0,
            Tracer: 1,
            Widowmaker: 0,
            Winston: 2,
            Zarya: 0,
            Zenyatta: 0
        },
        synergies: {
            Ana: 0,
            Bastion: 0,
            Doomfist: 0,
            Dva: 1,
            Genji: 2,
            Hanzo: 0,
            Junkrat: 0,
            Lucio: 2,
            McCree: 1,
            Mei: 0,
            Mercy: 0,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: 2,
            Reinhardt: 2,
            Roadhog: 1,
            Soldier76: 1,
            Sombra: 1,
            Symmetra: 1,
            Torbjorn: 0,
            Tracer: 0,
            Widowmaker: 0,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 1
        },
        score: 0,
        color: "298eff",
        proScore: 1,
        locked: false,
        removed: false
    }, {
        name: "Bastion",
        actualName: "Bastion",
        role: "Defense",
        healer: false,
        sniper: false,
        builder: false,
        counterScores: {
            Ana: 1,
            Bastion: 0,
            Doomfist: 0,
            Dva: 1,
            Genji: 2,
            Hanzo: 2,
            Junkrat: 2,
            Lucio: -1,
            McCree: 1,
            Mei: 1,
            Mercy: -2,
            Moira: 0,
            Orisa: 0,
            Pharah: 2,
            Reaper: 0,
            Reinhardt: -1,
            Roadhog: 1,
            Soldier76: 1,
            Sombra: 2,
            Symmetra: 0,
            Torbjorn: -2,
            Tracer: 2,
            Widowmaker: 2,
            Winston: -1,
            Zarya: 0,
            Zenyatta: 1
        },
        synergies: {
            Ana: 2,
            Bastion: 0,
            Doomfist: 0,
            Dva: -2,
            Genji: 2,
            Hanzo: -2,
            Junkrat: 2,
            Lucio: -1,
            McCree: -2,
            Mei: -2,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: -2,
            Reinhardt: 2,
            Roadhog: -2,
            Soldier76: -2,
            Sombra: -1,
            Symmetra: -2,
            Torbjorn: -2,
            Tracer: -2,
            Widowmaker: -2,
            Winston: -2,
            Zarya: 1,
            Zenyatta: 2
        },
        score: 0,
        color: "ebd9b3",
        proScore: -2,
        locked: false,
        removed: false
    },{
        name: "Brigitte",
        actualName: "Brigitte",
        role: "Support",
        healer: true,
        sniper: false,
        builder: false,
        counterScores: {
            Ana: 0,
            Bastion: 0,
            Dva: 0,
            Genji: 0,
            Hanzo: 0,
            Junkrat: 0,
            Lucio: 0,
            McCree: 0,
            Mei: 0,
            Mercy: 0,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: 0,
            Reinhardt: 0,
            Roadhog: 0,
            Soldier76: 0,
            Sombra: 0,
            Symmetra: 0,
            Torbjorn: 0,
            Tracer: 0,
            Widowmaker: 0,
            Winston: 0,
            Zarya: 0,
            Zenyatta: 0
        },
        synergies: {
            Ana: 0,
            Bastion: 0,
            Dva: 0,
            Genji: 0,
            Hanzo: 0,
            Junkrat: 0,
            Lucio: 0,
            McCree: 0,
            Mei: 0,
            Mercy: 0,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: 0,
            Reinhardt: 0,
            Roadhog: 0,
            Soldier76: 0,
            Sombra: 0,
            Symmetra: 0,
            Torbjorn: 0,
            Tracer: 0,
            Widowmaker: 0,
            Winston: 0,
            Zarya: 0,
            Zenyatta: 0
        },
        score: 0,
        color: "fedc57",
        proScore: -2,
        locked: false,
        removed: false
    }, {
        name: "Doomfist",
        actualName: "Doomfist",
        role: "Offense",
        healer: false,
        sniper: false,
        builder: false,
        counterScores: {
            Ana: 0,
            Bastion: 0,
            Doomfist: 0,
            Dva: 0,
            Genji: 0,
            Hanzo: 0,
            Junkrat: 0,
            Lucio: 0,
            McCree: 0,
            Mei: 0,
            Mercy: 0,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: 0,
            Reinhardt: 0,
            Roadhog: 0,
            Soldier76: 0,
            Sombra: 0,
            Symmetra: 0,
            Torbjorn: 0,
            Tracer: 0,
            Widowmaker: 0,
            Winston: 0,
            Zarya: 0,
            Zenyatta: 0
        },
        synergies: {
            Ana: 0,
            Bastion: 0,
            Doomfist: 0,
            Dva: 0,
            Genji: 0,
            Hanzo: 0,
            Junkrat: 0,
            Lucio: 0,
            McCree: 0,
            Mei: 0,
            Mercy: 0,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: 0,
            Reinhardt: 0,
            Roadhog: 0,
            Soldier76: 0,
            Sombra: 0,
            Symmetra: 0,
            Torbjorn: 0,
            Tracer: 0,
            Widowmaker: 0,
            Winston: 0,
            Zarya: 0,
            Zenyatta: 0
        },
        score: 0,
        color: "791e25",
        proScore: 0,
        locked: false,
        removed: false
    }, {
        name: "Dva",
        actualName: "D.Va",
        role: "Tank",
        healer: false,
        sniper: false,
        builder: false,
        counterScores: {
            Ana: 0,
            Bastion: 0,
            Doomfist: 0,
            Dva: 0,
            Genji: 0,
            Hanzo: 0,
            Junkrat: 1,
            Lucio: 0,
            McCree: 0,
            Mei: 2,
            Mercy: -2,
            Moira: 0,
            Orisa: 0,
            Pharah: -1,
            Reaper: 1,
            Reinhardt: 1,
            Roadhog: 0,
            Soldier76: 1,
            Sombra: 1,
            Symmetra: 0,
            Torbjorn: -2,
            Tracer: 0,
            Widowmaker: -1,
            Winston: -1,
            Zarya: 2,
            Zenyatta: 2
        },
        synergies: {
            Ana: 0,
            Bastion: -2,
            Dva: 0,
            Genji: -2,
            Hanzo: -2,
            Junkrat: -2,
            Lucio: 2,
            McCree: -2,
            Mei: -2,
            Mercy: 1,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: -2,
            Reinhardt: -2,
            Roadhog: -2,
            Soldier76: -2,
            Sombra: 0,
            Symmetra: -2,
            Torbjorn: -2,
            Tracer: 0,
            Widowmaker: 2,
            Winston: 1,
            Zarya: 2,
            Zenyatta: -1
        },
        score: 0,
        color: "feabe6",
        proScore: 1,
        locked: false,
        removed: false
    }, {
        name: "Genji",
        actualName: "Genji",
        role: "Offense",
        healer: false,
        sniper: false,
        builder: false,
        counterScores: {
            Ana: 0,
            Bastion: -1,
            Dva: 0,
            Genji: 0,
            Hanzo: -1,
            Junkrat: 0,
            Lucio: 0,
            McCree: 1,
            Mei: 2,
            Mercy: -2,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: 0,
            Reinhardt: 0,
            Roadhog: 2,
            Soldier76: 1,
            Sombra: 1,
            Symmetra: 2,
            Torbjorn: 0,
            Tracer: 1,
            Widowmaker: 0,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 1
        },
        synergies: {
            Ana: 1,
            Bastion: -2,
            Dva: -2,
            Genji: 0,
            Hanzo: 1,
            Junkrat: 2,
            Lucio: 2,
            McCree: -1,
            Mei: -2,
            Mercy: -2,
            Moira: 0,
            Orisa: 0,
            Pharah: 2,
            Reaper: 0,
            Reinhardt: -2,
            Roadhog: -2,
            Soldier76: 2,
            Sombra: 0,
            Symmetra: -2,
            Torbjorn: -2,
            Tracer: 2,
            Widowmaker: 1,
            Winston: 2,
            Zarya: 0,
            Zenyatta: 1
        },
        score: 0,
        color: "b6ef13",
        proScore: -1,
        locked: false,
        removed: false
    }, {
        name: "Hanzo",
        actualName: "Hanzo",
        role: "Defense",
        healer: false,
        sniper: true,
        builder: false,
        counterScores: {
            Ana: 1,
            Bastion: -1,
            Dva: 1,
            Genji: 1,
            Hanzo: 0,
            Junkrat: -1,
            Lucio: 0,
            McCree: 0,
            Mei: 1,
            Mercy: -2,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: 0,
            Reinhardt: 1,
            Roadhog: 1,
            Soldier76: 1,
            Sombra: 1,
            Symmetra: 1,
            Torbjorn: -1,
            Tracer: 1,
            Widowmaker: 1,
            Winston: 2,
            Zarya: 0,
            Zenyatta: -1
        },
        synergies: {
            Ana: -2,
            Bastion: -2,
            Dva: -2,
            Genji: 2,
            Hanzo: 0,
            Junkrat: -2,
            Lucio: 1,
            McCree: 2,
            Mei: -2,
            Mercy: 0,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: -2,
            Reinhardt: 1,
            Roadhog: -2,
            Soldier76: -2,
            Sombra: 0,
            Symmetra: -2,
            Torbjorn: -2,
            Tracer: -2,
            Widowmaker: 0,
            Winston: -2,
            Zarya: 2,
            Zenyatta: -2
        },
        score: 0,
        color: "ffeb96",
        proScore: -2,
        locked: false,
        removed: false
    }, {
        name: "Junkrat",
        actualName: "Junkrat",
        role: "Defense",
        healer: false,
        sniper: false,
        builder: false,
        counterScores: {
            Ana: 0,
            Bastion: -1,
            Dva: 1,
            Genji: 0,
            Hanzo: 1,
            Junkrat: 0,
            Lucio: 0,
            McCree: 1,
            Mei: 1,
            Mercy: -2,
            Moira: 0,
            Orisa: 0,
            Pharah: 2,
            Reaper: 0,
            Reinhardt: -1,
            Roadhog: 1,
            Soldier76: 1,
            Sombra: 0,
            Symmetra: -1,
            Torbjorn: 1,
            Tracer: 1,
            Widowmaker: 2,
            Winston: 0,
            Zarya: 2,
            Zenyatta: 0
        },
        synergies: {
            Ana: 1,
            Bastion: 2,
            Dva: -1,
            Genji: 2,
            Hanzo: 1,
            Junkrat: 0,
            Lucio: 1,
            McCree: 0,
            Mei: -2,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: -1,
            Reaper: 0,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 1,
            Sombra: 0,
            Symmetra: 1,
            Torbjorn: 1,
            Tracer: 0,
            Widowmaker: -2,
            Winston: 1,
            Zarya: 2,
            Zenyatta: 2
        },
        score: 0,
        color: "ffdc44",
        proScore: -2,
        locked: false,
        removed: false
    }, {
        name: "Lucio",
        actualName: "Lucio",
        role: "Support",
        healer: true,
        sniper: false,
        builder: false,
        counterScores: {
            Ana: 1,
            Bastion: 1,
            Dva: 1,
            Genji: 1,
            Hanzo: 1,
            Junkrat: 1,
            Lucio: 0,
            McCree: 2,
            Mei: 2,
            Mercy: -1,
            Moira: 0,
            Orisa: 0,
            Pharah: 2,
            Reaper: 0,
            Reinhardt: 1,
            Roadhog: 2,
            Soldier76: 1,
            Sombra: 2,
            Symmetra: 1,
            Torbjorn: 0,
            Tracer: 1,
            Widowmaker: 1,
            Winston: 2,
            Zarya: 1,
            Zenyatta: 0
        },
        synergies: {
            Ana: 2,
            Bastion: 0,
            Doomfist: 0,
            Dva: 1,
            Genji: 2,
            Hanzo: 0,
            Junkrat: 0,
            Lucio: 0,
            McCree: 2,
            Mei: 2,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 2,
            Reaper: 2,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 2,
            Sombra: 1,
            Symmetra: -2,
            Torbjorn: 0,
            Tracer: 2,
            Widowmaker: 0,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 2
        },
        score: 0,
        color: "b8ff45",
        proScore: 3,
        locked: false,
        removed: false
    }, {
        name: "McCree",
        actualName: "McCree",
        role: "Offense",
        healer: false,
        sniper: false,
        builder: false,
        counterScores: {
            Ana: 0,
            Bastion: 1,
            Dva: 1,
            Genji: 1,
            Hanzo: 1,
            Junkrat: 0,
            Lucio: 0,
            McCree: 0,
            Mei: 1,
            Mercy: -2,
            Moira: 0,
            Orisa: 0,
            Pharah: -1,
            Reaper: -1,
            Reinhardt: 0,
            Roadhog: 1,
            Soldier76: 0,
            Sombra: -1,
            Symmetra: -1,
            Torbjorn: 0,
            Tracer: -1,
            Widowmaker: 2,
            Winston: 0,
            Zarya: 0,
            Zenyatta: -1
        },
        synergies: {
            Ana: 1,
            Bastion: -2,
            Dva: -2,
            Genji: -1,
            Hanzo: -2,
            Junkrat: 2,
            Lucio: 2,
            McCree: 0,
            Mei: -2,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: 2,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 2,
            Sombra: 0,
            Symmetra: -2,
            Torbjorn: -2,
            Tracer: -2,
            Widowmaker: 2,
            Winston: -2,
            Zarya: 2,
            Zenyatta: 1
        },
        score: 0,
        color: "c23f46",
        proScore: -1,
        locked: false,
        removed: false
    }, {
        name: "Mei",
        actualName: "Mei",
        role: "Defense",
        healer: false,
        sniper: false,
        builder: false,
        counterScores: {
            Ana: 1,
            Bastion: 0,
            Doomfist: 0,
            Dva: -1,
            Genji: -1,
            Hanzo: 1,
            Junkrat: 1,
            Lucio: 0,
            McCree: 1,
            Mei: 0,
            Mercy: -2,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: 0,
            Reinhardt: 0,
            Roadhog: 0,
            Soldier76: 0,
            Sombra: 0,
            Symmetra: -1,
            Torbjorn: 0,
            Tracer: 2,
            Widowmaker: 1,
            Winston: 0,
            Zarya: 1,
            Zenyatta: 0
        },
        synergies: {
            Ana: 2,
            Bastion: -1,
            Dva: 1,
            Genji: 0,
            Hanzo: 1,
            Junkrat: 1,
            Lucio: 2,
            McCree: 1,
            Mei: 0,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: 2,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 1,
            Sombra: -1,
            Symmetra: 0,
            Torbjorn: 0,
            Tracer: 0,
            Widowmaker: -1,
            Winston: 0,
            Zarya: 2,
            Zenyatta: 1
        },
        score: 0,
        color: "87d7f6",
        proScore: 0,
        locked: false,
        removed: false
    }, {
        name: "Mercy",
        actualName: "Mercy",
        role: "Support",
        healer: true,
        sniper: false,
        builder: false,
        counterScores: {
            Ana: 2,
            Bastion: 2,
            Dva: 2,
            Genji: 2,
            Hanzo: 2,
            Junkrat: 2,
            Lucio: 0,
            McCree: 2,
            Mei: 2,
            Mercy: 0,
            Moira: 0,
            Orisa: 0,
            Pharah: 2,
            Reaper: 2,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 2,
            Sombra: 2,
            Symmetra: 2,
            Torbjorn: 1,
            Tracer: 2,
            Widowmaker: 2,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 2
        },
        synergies: {
            Ana: -1,
            Bastion: 2,
            Dva: 2,
            Genji: -1,
            Hanzo: 2,
            Junkrat: 2,
            Lucio: 2,
            McCree: 2,
            Mei: 1,
            Mercy: 0,
            Moira: 0,
            Orisa: 0,
            Pharah: 2,
            Reaper: 1,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 1,
            Sombra: -1,
            Symmetra: 2,
            Torbjorn: 2,
            Tracer: 2,
            Widowmaker: 2,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 0
        },
        score: 0,
        color: "fedc57",
        proScore: -2,
        locked: false,
        removed: false
    },{
        name: "Moira",
        actualName: "Moira",
        role: "Support",
        healer: true,
        sniper: false,
        builder: false,
        counterScores: {
            Ana: 0,
            Bastion: 0,
            Dva: 0,
            Genji: 0,
            Hanzo: 0,
            Junkrat: 0,
            Lucio: 0,
            McCree: 0,
            Mei: 0,
            Mercy: 0,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: 0,
            Reinhardt: 0,
            Roadhog: 0,
            Soldier76: 0,
            Sombra: 0,
            Symmetra: 0,
            Torbjorn: 0,
            Tracer: 0,
            Widowmaker: 0,
            Winston: 0,
            Zarya: 0,
            Zenyatta: 0
        },
        synergies: {
            Ana: 0,
            Bastion: 0,
            Dva: 0,
            Genji: 0,
            Hanzo: 0,
            Junkrat: 0,
            Lucio: 0,
            McCree: 0,
            Mei: 0,
            Mercy: 0,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: 0,
            Reinhardt: 0,
            Roadhog: 0,
            Soldier76: 0,
            Sombra: 0,
            Symmetra: 0,
            Torbjorn: 0,
            Tracer: 0,
            Widowmaker: 0,
            Winston: 0,
            Zarya: 0,
            Zenyatta: 0
        },
        score: 0,
        color: "fedc57",
        proScore: -2,
        locked: false,
        removed: false
    }, {
        name: "Orisa",
        actualName: "Orisa",
        role: "Tank",
        healer: false,
        sniper: false,
        builder: false,
        counterScores: {
            Ana: 0,
            Bastion: 0,
            Doomfist: 0,
            Dva: 0,
            Genji: 0,
            Hanzo: 0,
            Junkrat: 0,
            Lucio: 0,
            McCree: 0,
            Mei: 0,
            Mercy: 0,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: 0,
            Reinhardt: 0,
            Roadhog: 0,
            Soldier76: 0,
            Sombra: 0,
            Symmetra: 0,
            Torbjorn: 0,
            Tracer: 0,
            Widowmaker: 0,
            Winston: 0,
            Zarya: 0,
            Zenyatta: 0
        },
        synergies: {
            Ana: 0,
            Bastion: 0,
            Doomfist: 0,
            Dva: 0,
            Genji: 0,
            Hanzo: 0,
            Junkrat: 0,
            Lucio: 0,
            McCree: 0,
            Mei: 0,
            Mercy: 0,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: 0,
            Reinhardt: 0,
            Roadhog: 0,
            Soldier76: 0,
            Sombra: 0,
            Symmetra: 0,
            Torbjorn: 0,
            Tracer: 0,
            Widowmaker: 0,
            Winston: 0,
            Zarya: 0,
            Zenyatta: 0
        },
        score: 0,
        color: "efeae0",
        proScore: 0,
        locked: false,
        removed: false
    }, {
        name: "Pharah",
        actualName: "Pharah",
        role: "Offense",
        healer: false,
        sniper: false,
        builder: false,
        counterScores: {
            Ana: 1,
            Bastion: 0,
            Doomfist: 0,
            Dva: 1,
            Genji: 0,
            Hanzo: 0,
            Junkrat: -2,
            Lucio: -2,
            McCree: 2,
            Mei: -1,
            Mercy: -2,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: -1,
            Reinhardt: -1,
            Roadhog: 1,
            Soldier76: 2,
            Sombra: 1,
            Symmetra: -2,
            Torbjorn: 0,
            Tracer: 0,
            Widowmaker: 1,
            Winston: 0,
            Zarya: -1,
            Zenyatta: 1
        },
        synergies: {
            Ana: 2,
            Bastion: 0,
            Doomfist: 0,
            Dva: 0,
            Genji: 0,
            Hanzo: -1,
            Junkrat: -1,
            Lucio: 2,
            McCree: 0,
            Mei: 1,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: 0,
            Reinhardt: 0,
            Roadhog: 1,
            Soldier76: 1,
            Sombra: 2,
            Symmetra: -1,
            Torbjorn: -1,
            Tracer: -1,
            Widowmaker: -2,
            Winston: 1,
            Zarya: 2,
            Zenyatta: 1
        },
        score: 0,
        color: "3461a4",
        proScore: -2,
        locked: false,
        removed: false
    }, {
        name: "Reaper",
        actualName: "Reaper",
        role: "Offense",
        healer: false,
        sniper: false,
        builder: false,
        counterScores: {
            Ana: 0,
            Bastion: 1,
            Dva: 1,
            Genji: 0,
            Hanzo: 0,
            Junkrat: 1,
            Lucio: 1,
            McCree: 1,
            Mei: 1,
            Mercy: -2,
            Moira: 0,
            Orisa: 0,
            Pharah: 2,
            Reaper: 0,
            Reinhardt: 0,
            Roadhog: -1,
            Soldier76: 0,
            Sombra: 1,
            Symmetra: -1,
            Torbjorn: 0,
            Tracer: 1,
            Widowmaker: 1,
            Winston: -2,
            Zarya: -1,
            Zenyatta: 0
        },
        synergies: {
            Ana: 2,
            Bastion: 1,
            Dva: 0,
            Genji: -1,
            Hanzo: 2,
            Junkrat: 0,
            Lucio: 2,
            McCree: 2,
            Mei: 2,
            Mercy: 1,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: 0,
            Reinhardt: 2,
            Roadhog: 0,
            Soldier76: 0,
            Sombra: 0,
            Symmetra: -1,
            Torbjorn: 0,
            Tracer: 0,
            Widowmaker: 2,
            Winston: -1,
            Zarya: 2,
            Zenyatta: 2
        },
        score: 0,
        color: "333333 ",
        proScore: -2,
        locked: false,
        removed: false
    }, {
        name: "Reinhardt",
        actualName: "Reinhardt",
        role: "Tank",
        healer: false,
        sniper: false,
        builder: false,
        counterScores: {
            Ana: 1,
            Bastion: 2,
            Dva: 0,
            Genji: -1,
            Hanzo: 0,
            Junkrat: 2,
            Lucio: 1,
            McCree: 1,
            Mei: 1,
            Mercy: -2,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: 2,
            Reinhardt: 0,
            Roadhog: 2,
            Soldier76: 0,
            Sombra: 2,
            Symmetra: 1,
            Torbjorn: -1,
            Tracer: 2,
            Widowmaker: -2,
            Winston: 1,
            Zarya: 0,
            Zenyatta: 1
        },
        synergies: {
            Ana: 2,
            Bastion: 2,
            Dva: 1,
            Genji: 1,
            Hanzo: 1,
            Junkrat: 0,
            Lucio: 2,
            McCree: 2,
            Mei: -1,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: 2,
            Reinhardt: 0,
            Roadhog: 1,
            Soldier76: 2,
            Sombra: -1,
            Symmetra: -1,
            Torbjorn: -1,
            Tracer: 0,
            Widowmaker: 1,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 2
        },
        score: 0,
        color: "b9b5ad",
        proScore: 2,
        locked: false,
        removed: false
    }, {
        name: "Roadhog",
        actualName: "Roadhog",
        role: "Tank",
        healer: false,
        sniper: false,
        builder: false,
        counterScores: {
            Ana: 2,
            Bastion: -1,
            Dva: 1,
            Genji: 0,
            Hanzo: -1,
            Junkrat: 0,
            Lucio: -1,
            McCree: 0,
            Mei: 1,
            Mercy: -2,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: 2,
            Reinhardt: 0,
            Roadhog: 0,
            Soldier76: 1,
            Sombra: 2,
            Symmetra: -1,
            Torbjorn: -1,
            Tracer: 0,
            Widowmaker: 1,
            Winston: -1,
            Zarya: 1,
            Zenyatta: 2
        },
        synergies: {
            Ana: 1,
            Bastion: -2,
            Dva: -2,
            Genji: -2,
            Hanzo: -2,
            Junkrat: 2,
            Lucio: 1,
            McCree: -2,
            Mei: 2,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: -2,
            Reinhardt: -2,
            Roadhog: 0,
            Soldier76: -2,
            Sombra: -1,
            Symmetra: -2,
            Torbjorn: -2,
            Tracer: -2,
            Widowmaker: -2,
            Winston: -2,
            Zarya: -2,
            Zenyatta: -2
        },
        score: 0,
        color: "eedbb0",
        proScore: 1,
        locked: false,
        removed: false
    }, {
        name: "Soldier76",
        actualName: "Soldier: 76",
        role: "Offense",
        healer: false,
        sniper: false,
        builder: false,
        counterScores: {
            Ana: 1,
            Bastion: 0,
            Doomfist: 0,
            Dva: 1,
            Genji: 1,
            Hanzo: 0,
            Junkrat: 1,
            Lucio: 1,
            McCree: 1,
            Mei: 1,
            Mercy: -2,
            Moira: 0,
            Orisa: 0,
            Pharah: -1,
            Reaper: 0,
            Reinhardt: 1,
            Roadhog: 1,
            Soldier76: 0,
            Sombra: -1,
            Symmetra: -1,
            Torbjorn: 0,
            Tracer: 0,
            Widowmaker: 0,
            Winston: 0,
            Zarya: 0,
            Zenyatta: 0
        },
        synergies: {
            Ana: 2,
            Bastion: -1,
            Dva: 2,
            Genji: 2,
            Hanzo: 0,
            Junkrat: 1,
            Lucio: 2,
            McCree: -1,
            Mei: 1,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: 1,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 0,
            Sombra: 1,
            Symmetra: 2,
            Torbjorn: -1,
            Tracer: 0,
            Widowmaker: 0,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 2
        },
        score: 0,
        color: "525d9b",
        proScore: 0,
        locked: false,
        removed: false
    }, {
        name: "Sombra",
        actualName: "Sombra",
        role: "Offense",
        healer: false,
        sniper: false,
        builder: false,
        counterScores: {
            Ana: 0,
            Bastion: 0,
            Doomfist: 0,
            Dva: 1,
            Genji: 0,
            Hanzo: 1,
            Junkrat: 1,
            Lucio: -1,
            McCree: 2,
            Mei: 2,
            Mercy: -2,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: 0,
            Reinhardt: -1,
            Roadhog: 0,
            Soldier76: 2,
            Sombra: 0,
            Symmetra: 0,
            Torbjorn: 1,
            Tracer: 1,
            Widowmaker: 0,
            Winston: 2,
            Zarya: 1,
            Zenyatta: 0
        },
        synergies: {
            Ana: 0,
            Bastion: 0,
            Doomfist: 0,
            Dva: 0,
            Genji: 0,
            Hanzo: 0,
            Junkrat: 0,
            Lucio: 0,
            McCree: 0,
            Mei: 0,
            Mercy: 0,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: 0,
            Reinhardt: 0,
            Roadhog: 0,
            Soldier76: 0,
            Sombra: 0,
            Symmetra: 0,
            Torbjorn: 0,
            Tracer: 0,
            Widowmaker: 0,
            Winston: 0,
            Zarya: 0,
            Zenyatta: 0
        },
        score: 0,
        color: "bd7bf5",
        proScore: -2,
        locked: false,
        removed: false
    }, {
        name: "Symmetra",
        actualName: "Symmetra",
        role: "Support",
        healer: false,
        sniper: false,
        builder: true,
        counterScores: {
            Ana: 0,
            Bastion: 0,
            Doomfist: 0,
            Dva: -1,
            Genji: -2,
            Hanzo: 0,
            Junkrat: 2,
            Lucio: 0,
            McCree: 1,
            Mei: 2,
            Mercy: -2,
            Moira: 0,
            Orisa: 0,
            Pharah: 2,
            Reaper: 1,
            Reinhardt: -1,
            Roadhog: 1,
            Soldier76: 2,
            Sombra: 2,
            Symmetra: 0,
            Torbjorn: 1,
            Tracer: 0,
            Widowmaker: -1,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 0
        },
        synergies: {
            Ana: 1,
            Bastion: -2,
            Dva: -2,
            Genji: -2,
            Hanzo: -2,
            Junkrat: -2,
            Lucio: 1,
            McCree: -2,
            Mei: -2,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: -2,
            Reinhardt: -2,
            Roadhog: -2,
            Soldier76: -2,
            Sombra: -1,
            Symmetra: 0,
            Torbjorn: -1,
            Tracer: -2,
            Widowmaker: -2,
            Winston: -2,
            Zarya: -2,
            Zenyatta: 2
        },
        score: 0,
        color: "3cffff",
        proScore: -2,
        locked: false,
        removed: false
    }, {
        name: "Torbjorn",
        actualName: "Torbjorn",
        role: "Defense",
        healer: false,
        sniper: false,
        builder: true,
        counterScores: {
            Ana: 1,
            Bastion: 1,
            Dva: 2,
            Genji: 1,
            Hanzo: 1,
            Junkrat: 2,
            Lucio: 2,
            McCree: 0,
            Mei: 1,
            Mercy: -2,
            Moira: 0,
            Orisa: 0,
            Pharah: 2,
            Reaper: -1,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 2,
            Sombra: 0,
            Symmetra: 0,
            Torbjorn: 0,
            Tracer: -1,
            Widowmaker: 2,
            Winston: 1,
            Zarya: 1,
            Zenyatta: 2
        },
        synergies: {
            Ana: -2,
            Bastion: -2,
            Dva: -2,
            Genji: -2,
            Hanzo: 0,
            Junkrat: -2,
            Lucio: 1,
            McCree: -2,
            Mei: -2,
            Mercy: -2,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: -2,
            Reinhardt: 0,
            Roadhog: -2,
            Soldier76: -2,
            Sombra: -1,
            Symmetra: 2,
            Torbjorn: 0,
            Tracer: -2,
            Widowmaker: 2,
            Winston: -2,
            Zarya: 0,
            Zenyatta: 2
        },
        score: 0,
        color: "b04a33",
        proScore: -2,
        locked: false,
        removed: false
    }, {
        name: "Tracer",
        actualName: "Tracer",
        role: "Offense",
        healer: false,
        sniper: false,
        builder: false,
        counterScores: {
            Ana: -1,
            Bastion: -1,
            Dva: 0,
            Genji: 0,
            Hanzo: 0,
            Junkrat: 1,
            Lucio: 0,
            McCree: 2,
            Mei: 0,
            Mercy: -2,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: 0,
            Reinhardt: -1,
            Roadhog: 1,
            Soldier76: 1,
            Sombra: 1,
            Symmetra: 0,
            Torbjorn: 2,
            Tracer: 0,
            Widowmaker: 0,
            Winston: 1,
            Zarya: 0,
            Zenyatta: -1
        },
        synergies: {
            Ana: 0,
            Bastion: 0,
            Doomfist: 0,
            Dva: 0,
            Genji: 2,
            Hanzo: 0,
            Junkrat: 0,
            Lucio: 2,
            McCree: 0,
            Mei: 1,
            Mercy: -2,
            Moira: 0,
            Orisa: 0,
            Pharah: 2,
            Reaper: -1,
            Reinhardt: -1,
            Roadhog: 1,
            Soldier76: -1,
            Sombra: 1,
            Symmetra: -1,
            Torbjorn: 1,
            Tracer: 0,
            Widowmaker: 1,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 1
        },
        score: 0,
        color: "ffcf35",
        proScore: 0,
        locked: false,
        removed: false
    }, {
        name: "Widowmaker",
        actualName: "Widowmaker",
        role: "Defense",
        healer: false,
        sniper: true,
        builder: false,
        counterScores: {
            Ana: 0,
            Bastion: -1,
            Dva: 2,
            Genji: 1,
            Hanzo: 0,
            Junkrat: -2,
            Lucio: 0,
            McCree: -1,
            Mei: -1,
            Mercy: -2,
            Moira: 0,
            Orisa: 0,
            Pharah: -1,
            Reaper: -1,
            Reinhardt: 1,
            Roadhog: 0,
            Soldier76: 1,
            Sombra: 0,
            Symmetra: 0,
            Torbjorn: -1,
            Tracer: 1,
            Widowmaker: 0,
            Winston: 2,
            Zarya: -1,
            Zenyatta: -1
        },
        synergies: {
            Ana: -2,
            Bastion: -2,
            Dva: -2,
            Genji: -2,
            Hanzo: -2,
            Junkrat: -2,
            Lucio: 1,
            McCree: -2,
            Mei: -2,
            Mercy: -2,
            Moira: 0,
            Orisa: 0,
            Pharah: 2,
            Reaper: -2,
            Reinhardt: -2,
            Roadhog: -2,
            Soldier76: -2,
            Sombra: 0,
            Symmetra: 1,
            Torbjorn: 2,
            Tracer: -2,
            Widowmaker: 0,
            Winston: -2,
            Zarya: -2,
            Zenyatta: -2
        },
        score: 0,
        color: "b1b4db",
        proScore: -2,
        locked: false,
        removed: false
    }, {
        name: "Winston",
        actualName: "Winston",
        role: "Tank",
        healer: false,
        sniper: false,
        builder: false,
        counterScores: {
            Ana: -1,
            Bastion: 2,
            Dva: 2,
            Genji: -2,
            Hanzo: -1,
            Junkrat: 1,
            Lucio: 1,
            McCree: 1,
            Mei: 2,
            Mercy: -2,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: 2,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 2,
            Sombra: -1,
            Symmetra: -2,
            Torbjorn: 1,
            Tracer: 0,
            Widowmaker: -1,
            Winston: 0,
            Zarya: 2,
            Zenyatta: 2
        },
        synergies: {
            Ana: 2,
            Bastion: -2,
            Dva: -2,
            Genji: 2,
            Hanzo: -2,
            Junkrat: -2,
            Lucio: 2,
            McCree: -2,
            Mei: -2,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 2,
            Reaper: -2,
            Reinhardt: -2,
            Roadhog: -2,
            Soldier76: -2,
            Sombra: 0,
            Symmetra: -2,
            Torbjorn: -2,
            Tracer: 2,
            Widowmaker: 2,
            Winston: 0,
            Zarya: 1,
            Zenyatta: -2
        },
        score: 0,
        color: "e9d53e",
        proScore: -1,
        locked: false,
        removed: false
    }, {
        name: "Zarya",
        actualName: "Zarya",
        role: "Tank",
        healer: false,
        sniper: false,
        builder: false,
        counterScores: {
            Ana: 1,
            Bastion: 1,
            Dva: -1,
            Genji: -1,
            Hanzo: 1,
            Junkrat: -1,
            Lucio: 1,
            McCree: 0,
            Mei: 1,
            Mercy: -1,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: 1,
            Reinhardt: 0,
            Roadhog: 0,
            Soldier76: 1,
            Sombra: 2,
            Symmetra: -1,
            Torbjorn: -1,
            Tracer: 2,
            Widowmaker: 1,
            Winston: 0,
            Zarya: 0,
            Zenyatta: 1
        },
        synergies: {
            Ana: 2,
            Bastion: 1,
            Dva: 2,
            Genji: 2,
            Hanzo: 2,
            Junkrat: 1,
            Lucio: 2,
            McCree: 2,
            Mei: 1,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 2,
            Reaper: 2,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 1,
            Sombra: -1,
            Symmetra: 0,
            Torbjorn: 0,
            Tracer: 2,
            Widowmaker: 1,
            Winston: 2,
            Zarya: 0,
            Zenyatta: 2
        },
        score: 0,
        color: "ff73c1",
        proScore: 1,
        locked: false,
        removed: false
    }, {
        name: "Zenyatta",
        actualName: "Zenyatta",
        role: "Support",
        healer: true,
        sniper: false,
        builder: false,
        counterScores: {
            Ana: 2,
            Bastion: -1,
            Dva: 0,
            Genji: 2,
            Hanzo: 2,
            Junkrat: 1,
            Lucio: 1,
            McCree: 2,
            Mei: 1,
            Mercy: -2,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: 2,
            Reinhardt: 0,
            Roadhog: 1,
            Soldier76: 2,
            Sombra: 2,
            Symmetra: 0,
            Torbjorn: 1,
            Tracer: 2,
            Widowmaker: 2,
            Winston: 0,
            Zarya: 0,
            Zenyatta: 0
        },
        synergies: {
            Ana: 1,
            Bastion: 0,
            Doomfist: 0,
            Dva: 1,
            Genji: 2,
            Hanzo: 0,
            Junkrat: -1,
            Lucio: 2,
            McCree: 2,
            Mei: 1,
            Mercy: 1,
            Moira: 0,
            Orisa: 0,
            Pharah: 2,
            Reaper: 2,
            Reinhardt: 0,
            Roadhog: 1,
            Soldier76: 2,
            Sombra: 1,
            Symmetra: 1,
            Torbjorn: 1,
            Tracer: 2,
            Widowmaker: 2,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 0
        },
        score: 0,
        color: "6f241e",
        proScore: 0,
        locked: false,
        removed: false
    }
];

var mapData = [
    {
        name: "Hanamura",
        actualName: "Hanamura",
        mapType: "Assault",
        subMaps: {},
        attackHeroes: {
            Ana: 2,
            Bastion: -1,
            Dva: 2,
            Genji: 1,
            Hanzo: 0,
            Junkrat: 0,
            Lucio: 2,
            McCree: 2,
            Mei: 2,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: 1,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 1,
            Sombra: 1,
            Symmetra: -2,
            Torbjorn: -2,
            Tracer: 1,
            Widowmaker: 0,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 2
        },
        defenseHeroes: {
            Ana: 2,
            Bastion: 1,
            Dva: 1,
            Genji: 0,
            Hanzo: 1,
            Junkrat: 2,
            Lucio: 2,
            McCree: 2,
            Mei: 2,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: 1,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 1,
            Sombra: 2,
            Symmetra: 2,
            Torbjorn: 1,
            Tracer: 0,
            Widowmaker: 1,
            Winston: 0,
            Zarya: 2,
            Zenyatta: 2,
        }
    }, {
        name: "Horizon",
        actualName: "Horizon",
        mapType: "Assault",
        subMaps: {},
        attackHeroes: {
            Ana: 0,
            Bastion: 0,
            Doomfist: 0,
            Dva: 0,
            Genji: 0,
            Hanzo: 0,
            Junkrat: 0,
            Lucio: 0,
            McCree: 0,
            Mei: 0,
            Mercy: 0,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: 0,
            Reinhardt: 0,
            Roadhog: 0,
            Soldier76: 0,
            Sombra: 0,
            Symmetra: 0,
            Torbjorn: 0,
            Tracer: 0,
            Widowmaker: 0,
            Winston: 0,
            Zarya: 0,
            Zenyatta: 0
        },
        defenseHeroes: {
            Ana: 0,
            Bastion: 0,
            Doomfist: 0,
            Dva: 0,
            Genji: 0,
            Hanzo: 0,
            Junkrat: 0,
            Lucio: 0,
            McCree: 0,
            Mei: 0,
            Mercy: 0,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: 0,
            Reinhardt: 0,
            Roadhog: 0,
            Soldier76: 0,
            Sombra: 0,
            Symmetra: 0,
            Torbjorn: 0,
            Tracer: 0,
            Widowmaker: 0,
            Winston: 0,
            Zarya: 0,
            Zenyatta: 0
        }
    }, {
        name: "BlizzardWorld",
        actualName: "BlizzardWorld",
        mapType: "Hybrid",
        subMaps: {},
        attackHeroes: {
            Ana: 0,
            Bastion: 0,
            Doomfist: 0,
            Dva: 0,
            Genji: 0,
            Hanzo: 0,
            Junkrat: 0,
            Lucio: 0,
            McCree: 0,
            Mei: 0,
            Mercy: 0,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: 0,
            Reinhardt: 0,
            Roadhog: 0,
            Soldier76: 0,
            Sombra: 0,
            Symmetra: 0,
            Torbjorn: 0,
            Tracer: 0,
            Widowmaker: 0,
            Winston: 0,
            Zarya: 0,
            Zenyatta: 0
        },
        defenseHeroes: {
            Ana: 0,
            Bastion: 0,
            Doomfist: 0,
            Dva: 0,
            Genji: 0,
            Hanzo: 0,
            Junkrat: 0,
            Lucio: 0,
            McCree: 0,
            Mei: 0,
            Mercy: 0,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: 0,
            Reinhardt: 0,
            Roadhog: 0,
            Soldier76: 0,
            Sombra: 0,
            Symmetra: 0,
            Torbjorn: 0,
            Tracer: 0,
            Widowmaker: 0,
            Winston: 0,
            Zarya: 0,
            Zenyatta: 0
        }
    }, {
        name: "Junkertown",
        actualName: "Junkertown",
        mapType: "Escort",
        subMaps: {},
        attackHeroes: {
            Ana: 0,
            Bastion: 0,
            Doomfist: 0,
            Dva: 0,
            Genji: 0,
            Hanzo: 0,
            Junkrat: 0,
            Lucio: 0,
            McCree: 0,
            Mei: 0,
            Mercy: 0,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: 0,
            Reinhardt: 0,
            Roadhog: 0,
            Soldier76: 0,
            Sombra: 0,
            Symmetra: 0,
            Torbjorn: 0,
            Tracer: 0,
            Widowmaker: 0,
            Winston: 0,
            Zarya: 0,
            Zenyatta: 0
        },
        defenseHeroes: {
            Ana: 0,
            Bastion: 0,
            Doomfist: 0,
            Dva: 0,
            Genji: 0,
            Hanzo: 0,
            Junkrat: 0,
            Lucio: 0,
            McCree: 0,
            Mei: 0,
            Mercy: 0,
            Moira: 0,
            Orisa: 0,
            Pharah: 0,
            Reaper: 0,
            Reinhardt: 0,
            Roadhog: 0,
            Soldier76: 0,
            Sombra: 0,
            Symmetra: 0,
            Torbjorn: 0,
            Tracer: 0,
            Widowmaker: 0,
            Winston: 0,
            Zarya: 0,
            Zenyatta: 0
        }
    }, {
        name: "TempleofAnubis",
        actualName: "Anubis",
        mapType: "Assault",
        subMaps: {},
        attackHeroes: {
            Ana: 2,
            Bastion: -1,
            Dva: 2,
            Genji: 1,
            Hanzo: 0,
            Junkrat: 1,
            Lucio: 2,
            McCree: 1,
            Mei: 1,
            Mercy: 1,
            Moira: 0,
            Orisa: 0,
            Pharah: 2,
            Reaper: 2,
            Reinhardt: 2,
            Roadhog: 1,
            Soldier76: 1,
            Sombra: 1,
            Symmetra: -2,
            Torbjorn: -1,
            Tracer: 1,
            Widowmaker: 1,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 2
        },
        defenseHeroes: {
            Ana: 2,
            Bastion: 1,
            Dva: 2,
            Genji: 0,
            Hanzo: 1,
            Junkrat: 2,
            Lucio: 2,
            McCree: 2,
            Mei: 2,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: 1,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 1,
            Sombra: 2,
            Symmetra: 1,
            Torbjorn: 1,
            Tracer: 0,
            Widowmaker: 1,
            Winston: 1,
            Zarya: 2,
            Zenyatta: 2,
        }
    }, {
        name: "VolskayaIndustries",
        actualName: "Volskaya",
        mapType: "Assault",
        subMaps: {},
        attackHeroes: {
            Ana: 2,
            Bastion: -1,
            Dva: 2,
            Genji: 1,
            Hanzo: 0,
            Junkrat: 0,
            Lucio: 2,
            McCree: 2,
            Mei: 1,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: 2,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 1,
            Sombra: 0,
            Symmetra: -1,
            Torbjorn: -2,
            Tracer: 2,
            Widowmaker: 0,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 2
        },
        defenseHeroes: {
            Ana: 2,
            Bastion: 1,
            Dva: 1,
            Genji: 0,
            Hanzo: 1,
            Junkrat: 2,
            Lucio: 2,
            McCree: 2,
            Mei: 2,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: 1,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 1,
            Sombra: 2,
            Symmetra: 1,
            Torbjorn: 1,
            Tracer: 0,
            Widowmaker: 1,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 2,
        }
    }, {
        name: "Dorado",
        actualName: "Dorado",
        mapType: "Escort",
        subMaps: {},
        attackHeroes: {
            Ana: 2,
            Bastion: 0,
            Doomfist: 0,
            Dva: 1,
            Genji: 1,
            Hanzo: 0,
            Junkrat: 1,
            Lucio: 2,
            McCree: 2,
            Mei: 1,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 2,
            Reaper: 2,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 1,
            Sombra: 2,
            Symmetra: -1,
            Torbjorn: -1,
            Tracer: 2,
            Widowmaker: 0,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 2
        },
        defenseHeroes: {
            Ana: 2,
            Bastion: 0,
            Doomfist: 0,
            Dva: 1,
            Genji: 0,
            Hanzo: 2,
            Junkrat: 2,
            Lucio: 2,
            McCree: 2,
            Mei: 1,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: 1,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 1,
            Sombra: 2,
            Symmetra: 0,
            Torbjorn: 0,
            Tracer: 1,
            Widowmaker: 1,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 2,
        }
    }, {
        name: "Route66",
        actualName: "Route 66",
        mapType: "Escort",
        subMaps: {},
        attackHeroes: {
            Ana: 2,
            Bastion: 0,
            Doomfist: 0,
            Dva: 2,
            Genji: 1,
            Hanzo: 1,
            Junkrat: 0,
            Lucio: 2,
            McCree: 2,
            Mei: 1,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: 2,
            Reinhardt: 2,
            Roadhog: 1,
            Soldier76: 1,
            Sombra: 2,
            Symmetra: -2,
            Torbjorn: -1,
            Tracer: 2,
            Widowmaker: 0,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 2
        },
        defenseHeroes: {
            Ana: 2,
            Bastion: 0,
            Doomfist: 0,
            Dva: 2,
            Genji: 0,
            Hanzo: 2,
            Junkrat: 1,
            Lucio: 2,
            McCree: 2,
            Mei: 2,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: 2,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 0,
            Sombra: 2,
            Symmetra: 0,
            Torbjorn: 1,
            Tracer: 1,
            Widowmaker: 1,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 2,
        }
    }, {
        name: "WatchpointGibraltar",
        actualName: "Gibraltar",
        mapType: "Escort",
        subMaps: {},
        attackHeroes: {
            Ana: 2,
            Bastion: 0,
            Doomfist: 0,
            Dva: 1,
            Genji: 1,
            Hanzo: 0,
            Junkrat: 0,
            Lucio: 2,
            McCree: 2,
            Mei: 1,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 2,
            Reaper: 2,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 2,
            Sombra: 0,
            Symmetra: -2,
            Torbjorn: -1,
            Tracer: 1,
            Widowmaker: 1,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 2
        },
        defenseHeroes: {
            Ana: 2,
            Bastion: 1,
            Dva: 1,
            Genji: 0,
            Hanzo: 2,
            Junkrat: 2,
            Lucio: 2,
            McCree: 2,
            Mei: 1,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: 1,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 1,
            Sombra: 1,
            Symmetra: 0,
            Torbjorn: 1,
            Tracer: 0,
            Widowmaker: 1,
            Winston: 1,
            Zarya: 2,
            Zenyatta: 2,
        }
    }, {
        name: "Hollywood",
        actualName: "Hollywood",
        mapType: "Hybrid",
        subMaps: {},
        attackHeroes: {
            Ana: 2,
            Bastion: -1,
            Dva: 2,
            Genji: 1,
            Hanzo: 1,
            Junkrat: 1,
            Lucio: 2,
            McCree: 2,
            Mei: 1,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 2,
            Reaper: 2,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 1,
            Sombra: 1,
            Symmetra: -2,
            Torbjorn: -2,
            Tracer: 2,
            Widowmaker: 1,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 2
        },
        defenseHeroes: {
            Ana: 2,
            Bastion: 1,
            Dva: 2,
            Genji: 0,
            Hanzo: 1,
            Junkrat: 2,
            Lucio: 2,
            McCree: 2,
            Mei: 2,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: 2,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 1,
            Sombra: 1,
            Symmetra: 1,
            Torbjorn: 1,
            Tracer: 1,
            Widowmaker: 0,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 2,
        }
    }, {
        name: "KingsRow",
        actualName: "KingsRow",
        mapType: "Hybrid",
        subMaps: {},
        attackHeroes: {
            Ana: 2,
            Bastion: 1,
            Dva: 2,
            Genji: 1,
            Hanzo: 2,
            Junkrat: 1,
            Lucio: 2,
            McCree: 2,
            Mei: 1,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 2,
            Reaper: 2,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 1,
            Sombra: 2,
            Symmetra: -2,
            Torbjorn: -1,
            Tracer: 2,
            Widowmaker: 2,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 2
        },
        defenseHeroes: {
            Ana: 2,
            Bastion: 0,
            Doomfist: 0,
            Dva: 1,
            Genji: 0,
            Hanzo: 2,
            Junkrat: 2,
            Lucio: 2,
            McCree: 2,
            Mei: 2,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: 2,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 1,
            Sombra: 1,
            Symmetra: 2,
            Torbjorn: 1,
            Tracer: 2,
            Widowmaker: 1,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 2,
        }
    }, {
        name: "Numbani",
        actualName: "Numbani",
        mapType: "Hybrid",
        subMaps: {},
        attackHeroes: {
            Ana: 2,
            Bastion: 0,
            Doomfist: 0,
            Dva: 2,
            Genji: 1,
            Hanzo: 1,
            Junkrat: 0,
            Lucio: 2,
            McCree: 2,
            Mei: 2,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 2,
            Reaper: 2,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 1,
            Sombra: 2,
            Symmetra: -2,
            Torbjorn: -1,
            Tracer: 2,
            Widowmaker: 0,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 2
        },
        defenseHeroes: {
            Ana: 2,
            Bastion: 1,
            Dva: 1,
            Genji: 0,
            Hanzo: 2,
            Junkrat: 2,
            Lucio: 2,
            McCree: 2,
            Mei: 2,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 1,
            Reaper: 1,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 1,
            Sombra: 1,
            Symmetra: 1,
            Torbjorn: 1,
            Tracer: 1,
            Widowmaker: 1,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 2,
        }
    }, {
        name: "Eichenwalde",
        actualName: "Eichenwalde",
        mapType: "Hybrid",
        subMaps: {},
        attackHeroes: {
            Ana: 2,
            Bastion: 0,
            Doomfist: 0,
            Dva: 2,
            Genji: 1,
            Hanzo: 1,
            Junkrat: 1,
            Lucio: 2,
            McCree: 1,
            Mei: 1,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 2,
            Reaper: 2,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 1,
            Sombra: 2,
            Symmetra: -2,
            Torbjorn: -2,
            Tracer: 2,
            Widowmaker: 0,
            Winston: 2,
            Zarya: 2,
            Zenyatta: 2
        },
        defenseHeroes: {
            Ana: 2,
            Bastion: 1,
            Dva: 1,
            Genji: 0,
            Hanzo: 2,
            Junkrat: 2,
            Lucio: 2,
            McCree: 2,
            Mei: 2,
            Mercy: 2,
            Moira: 0,
            Orisa: 0,
            Pharah: 2,
            Reaper: 2,
            Reinhardt: 2,
            Roadhog: 2,
            Soldier76: 1,
            Sombra: 2,
            Symmetra: 2,
            Torbjorn: 1,
            Tracer: 1,
            Widowmaker: 1,
            Winston: 1,
            Zarya: 2,
            Zenyatta: 2,
        }
    }, {
        name: "Oasis",
        actualName: "Oasis",
        mapType: "Control",
        subMaps: {
            CityCenter: {
                name: "CityCenter",
                subActualName: "CityCenter",
                heroes: {
                    Ana: 2,
                    Bastion: 0,
                    Doomfist: 0,
                    Dva: 2,
                    Genji: 1,
                    Hanzo: 0,
                    Junkrat: 1,
                    Lucio: 2,
                    McCree: 2,
                    Mei: 2,
                    Mercy: 0,
                    Moira: 0,
                    Orisa: 0,
                    Pharah: 1,
                    Reaper: 2,
                    Reinhardt: 1,
                    Roadhog: 2,
                    Soldier76: 1,
                    Sombra: 1,
                    Symmetra: -2,
                    Torbjorn: -1,
                    Tracer: 2,
                    Widowmaker: -1,
                    Winston: 2,
                    Zarya: 2,
                    Zenyatta: 2
                }
            },
            Gardens: {
                name: "Gardens",
                subActualName: "Gardens",
                heroes: {
                    Ana: 2,
                    Bastion: -1,
                    Dva: 2,
                    Genji: 1,
                    Hanzo: 0,
                    Junkrat: 2,
                    Lucio: 2,
                    McCree: 2,
                    Mei: 2,
                    Mercy: 1,
                    Moira: 0,
                    Orisa: 0,
                    Pharah: 1,
                    Reaper: 2,
                    Reinhardt: 2,
                    Roadhog: 2,
                    Soldier76: 1,
                    Sombra: 1,
                    Symmetra: -1,
                    Torbjorn: -1,
                    Tracer: 2,
                    Widowmaker: -1,
                    Winston: 2,
                    Zarya: 2,
                    Zenyatta: 2
                }
            },
            University: {
                name: "University",
                subActualName: "University",
                heroes: {
                    Ana: 2,
                    Bastion: 0,
                    Doomfist: 0,
                    Dva: 2,
                    Genji: 1,
                    Hanzo: 1,
                    Junkrat: 1,
                    Lucio: 2,
                    McCree: 2,
                    Mei: 2,
                    Mercy: 1,
                    Moira: 0,
                    Orisa: 0,
                    Pharah: 1,
                    Reaper: 2,
                    Reinhardt: 1,
                    Roadhog: 2,
                    Soldier76: 1,
                    Sombra: 2,
                    Symmetra: -1,
                    Torbjorn: -1,
                    Tracer: 2,
                    Widowmaker: -1,
                    Winston: 2,
                    Zarya: 2,
                    Zenyatta: 2
                }
            }
        },
        attackHeroes: {},
        defenseHeroes: {}
    }, {
        name: "Ilios",
        actualName: "Ilios",
        mapType: "Control",
        subMaps: {
            Lighthouse: {
                name: "Lighthouse",
                subActualName: "Lighthouse",
                heroes: {
                    Ana: 2,
                    Bastion: -1,
                    Dva: 2,
                    Genji: 1,
                    Hanzo: 0,
                    Junkrat: 1,
                    Lucio: 2,
                    McCree: 2,
                    Mei: 2,
                    Mercy: 1,
                    Moira: 0,
                    Orisa: 0,
                    Pharah: 1,
                    Reaper: 2,
                    Reinhardt: 1,
                    Roadhog: 2,
                    Soldier76: 1,
                    Sombra: 1,
                    Symmetra: -1,
                    Torbjorn: -2,
                    Tracer: 2,
                    Widowmaker: -1,
                    Winston: 2,
                    Zarya: 2,
                    Zenyatta: 2
                }
            },
            Ruins: {
                name: "Ruins",
                subActualName: "Ruins",
                heroes: {
                    Ana: 2,
                    Bastion: 0,
                    Doomfist: 0,
                    Dva: 2,
                    Genji: 1,
                    Hanzo: 0,
                    Junkrat: 1,
                    Lucio: 2,
                    McCree: 2,
                    Mei: 2,
                    Mercy: 0,
                    Moira: 0,
                    Orisa: 0,
                    Pharah: 1,
                    Reaper: 2,
                    Reinhardt: 2,
                    Roadhog: 2,
                    Soldier76: 1,
                    Sombra: 2,
                    Symmetra: -2,
                    Torbjorn: -1,
                    Tracer: 2,
                    Widowmaker: 1,
                    Winston: 2,
                    Zarya: 2,
                    Zenyatta: 2
                }
            },
            Well: {
                name: "Well",
                subActualName: "Well",
                heroes: {
                    Ana: 2,
                    Bastion: -1,
                    Dva: 2,
                    Genji: 1,
                    Hanzo: 0,
                    Junkrat: 0,
                    Lucio: 2,
                    McCree: 2,
                    Mei: 2,
                    Mercy: 1,
                    Moira: 0,
                    Orisa: 0,
                    Pharah: 2,
                    Reaper: 2,
                    Reinhardt: 2,
                    Roadhog: 2,
                    Soldier76: 1,
                    Sombra: 2,
                    Symmetra: -2,
                    Torbjorn: -2,
                    Tracer: 2,
                    Widowmaker: 0,
                    Winston: 2,
                    Zarya: 2,
                    Zenyatta: 2
                }
            }
        },
        attackHeroes: {},
        defenseHeroes: {}
    }, {
        name: "LijangTower",
        actualName: "Lijang",
        mapType: "Control",
        subMaps: {
            ControlCenter: {
                name: "ControlCenter",
                subActualName: "Control Center",
                heroes: {
                    Ana: 2,
                    Bastion: 0,
                    Doomfist: 0,
                    Dva: 1,
                    Genji: 1,
                    Hanzo: 0,
                    Junkrat: 1,
                    Lucio: 2,
                    McCree: 2,
                    Mei: 2,
                    Mercy: 1,
                    Moira: 0,
                    Orisa: 0,
                    Pharah: 1,
                    Reaper: 2,
                    Reinhardt: 2,
                    Roadhog: 2,
                    Soldier76: 1,
                    Sombra: 1,
                    Symmetra: -2,
                    Torbjorn: -1,
                    Tracer: 2,
                    Widowmaker: -1,
                    Winston: 1,
                    Zarya: 2,
                    Zenyatta: 2
                }
            },
            Garden: {
                name: "Garden",
                subActualName: "Garden",
                heroes: {
                    Ana: 2,
                    Bastion: -1,
                    Dva: 1,
                    Genji: 1,
                    Hanzo: 0,
                    Junkrat: 1,
                    Lucio: 2,
                    McCree: 1,
                    Mei: 2,
                    Mercy: 0,
                    Moira: 0,
                    Orisa: 0,
                    Pharah: 2,
                    Reaper: 2,
                    Reinhardt: 1,
                    Roadhog: 2,
                    Soldier76: 1,
                    Sombra: 1,
                    Symmetra: -2,
                    Torbjorn: -1,
                    Tracer: 2,
                    Widowmaker: -2,
                    Winston: 2,
                    Zarya: 2,
                    Zenyatta: 2
                }
            },
            NightMarket: {
                name: "NightMarket",
                subActualName: "Night Market",
                heroes: {
                    Ana: 2,
                    Bastion: -1,
                    Dva: 2,
                    Genji: 1,
                    Hanzo: 0,
                    Junkrat: 2,
                    Lucio: 2,
                    McCree: 1,
                    Mei: 2,
                    Mercy: 1,
                    Moira: 0,
                    Orisa: 0,
                    Pharah: 2,
                    Reaper: 2,
                    Reinhardt: 1,
                    Roadhog: 2,
                    Soldier76: 1,
                    Sombra: 1,
                    Symmetra: -2,
                    Torbjorn: -1,
                    Tracer: 2,
                    Widowmaker: -2,
                    Winston: 1,
                    Zarya: 2,
                    Zenyatta: 2
                }
            }
        },
        attackHeroes: {},
        defenseHeroes: {}
    }, {
        name: "Nepal",
        actualName: "Nepal",
        mapType: "Control",
        subMaps: {
            Sanctum: {
                name: "Sanctum",
                subActualName: "Sanctum",
                heroes: {
                    Ana: 2,
                    Bastion: 0,
                    Doomfist: 0,
                    Dva: 2,
                    Genji: 1,
                    Hanzo: 0,
                    Junkrat: 1,
                    Lucio: 2,
                    McCree: 2,
                    Mei: 2,
                    Mercy: 0,
                    Moira: 0,
                    Orisa: 0,
                    Pharah: 1,
                    Reaper: 2,
                    Reinhardt: 1,
                    Roadhog: 2,
                    Soldier76: 1,
                    Sombra: 1,
                    Symmetra: -2,
                    Torbjorn: -1,
                    Tracer: 2,
                    Widowmaker: -1,
                    Winston: 2,
                    Zarya: 2,
                    Zenyatta: 2
                }
            },
            Temple: {
                name: "Temple",
                subActualName: "Temple",
                heroes: {
                    Ana: 2,
                    Bastion: -1,
                    Dva: 2,
                    Genji: 1,
                    Hanzo: 0,
                    Junkrat: 2,
                    Lucio: 2,
                    McCree: 2,
                    Mei: 2,
                    Mercy: 1,
                    Moira: 0,
                    Orisa: 0,
                    Pharah: 1,
                    Reaper: 2,
                    Reinhardt: 2,
                    Roadhog: 2,
                    Soldier76: 1,
                    Sombra: 1,
                    Symmetra: -1,
                    Torbjorn: -1,
                    Tracer: 2,
                    Widowmaker: -1,
                    Winston: 2,
                    Zarya: 2,
                    Zenyatta: 2
                }
            },
            Village: {
                name: "Village",
                subActualName: "Village",
                heroes: {
                    Ana: 2,
                    Bastion: 0,
                    Doomfist: 0,
                    Dva: 2,
                    Genji: 1,
                    Hanzo: 1,
                    Junkrat: 1,
                    Lucio: 2,
                    McCree: 2,
                    Mei: 2,
                    Mercy: 1,
                    Moira: 0,
                    Orisa: 0,
                    Pharah: 1,
                    Reaper: 2,
                    Reinhardt: 1,
                    Roadhog: 2,
                    Soldier76: 1,
                    Sombra: 2,
                    Symmetra: -1,
                    Torbjorn: -1,
                    Tracer: 2,
                    Widowmaker: -1,
                    Winston: 2,
                    Zarya: 2,
                    Zenyatta: 2
                }
            }
        },
        attackHeroes: {},
        defenseHeroes: {}
    }
];

var metaData = [
    {
        name: "2 Tank, 2 Healers, 2 Offense",
        value: "TwoTwoTwoMeta",
        Support: 0,
        Attack: 0,
        Defense: 0,
        Tank: 0
    }, {
        name: "3 Tank, 3 Support",
        value: "TankMeta",
        Support: 3,
        Attack: 0,
        Defense: 0,
        Tank: 3
    }, {
        name: "3 Tank, 2 Healers, 1 Offense",
        value: "321Meta",
        Support: 2,
        Attack: 1,
        Defense: 0,
        Tank: 3
    }, {
        name: "2 Tank, 2 Healer, 2 Offense/Defense",
        value: "attackDefenseMeta",
        Support: 2,
        Attack: 2,
        Defense: 2,
        Tank: 2
    }, {
        name: "No Meta",
        value: "NoMeta",
        Support: 6,
        Attack: 6,
        Defense: 6,
        Tank: 6
    }, {
        name: "One of Each Role",
        value: "oneOfEachMeta",
        Support: 6,
        Attack: 6,
        Defense: 6,
        Tank: 6
    }, {
        name: "Hanzo Meta",
        value: "hanzoMeta",
        Support: 6,
        Attack: 6,
        Defense: 6,
        Tank: 6
    }
];
//Increments by 1 the Hero by the counterWeight
function incrementHeroByName(_hero, amount) {
    heroData.filter(function (val, index, array) {
        return val.name === _hero;
    })[0].score = heroData.filter(function (val, index, array) {
        return val.name === _hero;
    })[0].score + amount;
}

//Returns an array of strings of all the hero weaknesses
function getHeroWeaknessesByName(_hero) {
    return heroData.filter(function (val, index, array) {
        return val.name === _hero;
    })[0].weaknesses;
}

//Returns an array of strings of all the hero strengths
function getHeroStrengthsByName(_hero) {
    return heroData.filter(function (val, index, array) {
        return val.name === _hero;
    })[0].strengths;
}

//Returns the mapType as a string
function getMapTypeByName(_map) {
    return mapData.filter(function (val, index, array) {
        return val.name === _map;
    })[0].mapType;
}

//Get all the heroes good on the map
function getMapHeroesByName() {
    var _map = $(".selected").attr('map');
    if (_map != null) {
        var mapType = getMapTypeByName(_map);
        var mapIsAttack = document.getElementById("attackCheckbox").checked;
        var subMaps = mapData.filter(function (val, index, array) {
            return val.name === _map;
        })[0].subMaps;
        var subMapLength = document.getElementById("subMapDropdown").length;
        var subMapDropdown = document.getElementById("subMapDropdown");
        var selectedSubMap = subMapDropdown.options[subMapDropdown.selectedIndex].value;
        $("#subMapDropdown").empty();
        $("#subMapDropdown").append("<option value=\"NoSubMap\">Average of all maps</option>");
        for (var subMap in subMaps) {
            var option = document.createElement("option");
            option.value = subMaps[subMap].name;
            option.text = subMaps[subMap].subActualName;
            subMapDropdown.add(option);
        }
        $("#subMapDropdown").val(selectedSubMap);
        if (mapType == "Control") { //If map is control return the heroes for the subtype
            $("#subMapDropdownContainer").css("display", "inline-block");
            if (selectedSubMap != "NoSubMap")
                return subMaps[selectedSubMap].heroes;
            else { //Figure out the average score for each hero
                var averageArray = subMaps[subMapDropdown.options[1].value].heroes;
                var first = true;
                for (subMap in subMaps) {
                    if (!first) {
                        var tempArray = subMaps[subMap].heroes;
                        for (hero in tempArray) {
                            averageArray[hero] += tempArray[hero]
                        }
                    }
                    first = false;
                }
                for (score in averageArray)
                    averageArray[score] = averageArray[score] / 3
                return averageArray;
            }
        } else if (mapIsAttack) //If attack is selected
            return mapData.filter(function (val, index, array) {
                return val.name === _map;
            })[0].attackHeroes;
        else //If defense.
            return mapData.filter(function (val, index, array) {
                return val.name === _map;
            })[0].defenseHeroes;
    } else
        return [];
}

//Returns an array of six heroes as objects sorted by score
function getTopSixHeroesArray() {
    var arrayToReturn = [];
    var heroesAlreadyAdded = [];

    heroData.forEach(function (obj, index) {
        if (obj.locked) {
            heroesAlreadyAdded.push(obj.name);
            arrayToReturn.push(obj);
        }
    });
    var tempArray = heroData.sort(function (a, b) {
        return a.score - b.score;
    }).reverse().slice(0);
    tempArray.forEach(function (obj) {
        if (!obj.removed && !obj.locked)
            arrayToReturn.push(obj)
    });
    return arrayToReturn.splice(0, 6);
}

//Returns an array of objects filled with all heroes sorted by score from highest to lowest
function getAllHeroesArray() {
    return heroData.sort(function (a, b) {
        return a.score - b.score;
    }).reverse().slice(0);
}

//Returns an object of the selected hero
function getHeroByName(_hero) {
    return heroData.filter(function (val, index, array) {
        return val.name === _hero;
    })[0];
}

//Returns all heroes of a given role as an array of objects
function getSortedRoleByName(roleToSearch) {
    var tempArray = new Array();
    if (roleToSearch)
        heroData.forEach(function (hero, index) {
            if (hero.role == roleToSearch)
                tempArray.push(hero)
        });
    return tempArray;
}

//Returns an array of objects of all heroes marked as healers
function getHealersArray() {
    var tempArray = new Array();
    heroData.forEach(function (hero, index) {
        if (hero.healer)
            tempArray.push(hero)
    });
    return tempArray;
}

//Testing, logs to the console all the hero's scores
function printEachHeroScore() {
    console.log("New List:");
    heroData.sort(compare);
    for (var i = 0; i < heroData.length; i++)
        console.log(heroData[i].name + "'s score: " + heroData[i].score);
    console.log("");
}

function compare(a, b) {
    if (a.score < b.score)
        return 1;
    if (a.score > b.score)
        return -1;
    return 0;
}

function resetHeroScores() {
    heroData.forEach(function (obj, index) {
        if (document.getElementById("tournamentCheckbox").checked)
            obj.score = obj.proScore * tournamentWeight;
        else obj.score = 0;
    });
}

function resetRemovedHeroes() {
    heroData.forEach(function (obj, index) {
        obj.removed = false;
    });
    resetRemovedHeroesBackgroundColor();
}

function removeHero(_hero) {
    if (_hero != "")
        heroData.filter(function (val, index, array) {
            return val.name === _hero;
        })[0].removed = true;
}

function lockHero(_hero, setting) {
    if (_hero != "")
        heroData.filter(function (val, index, array) {
            return val.name === _hero;
        })[0].locked = setting;
}

function getAllLockedHeroes() {
    var tempArray = [];
    heroData.forEach(function (obj, index) {
        if (obj.locked)
            tempArray.push(obj);
    });
    return tempArray;
}

function resetLockedHeroes() {
    heroData.forEach(function (obj, index) {
        obj.locked = false;
    });
    $(".fa-unlock").each(function (index, obj) {
        $(obj).removeClass("fa-unlock");
        $(obj).addClass("fa-lock");
    });
}

function countLockedHeroes() {
    var x = 0;
    heroData.forEach(function (obj, index) {
        if (obj.locked)
            x = x + 1;
    });
    return x;
}
